version: 2.2.1-SNAPSHOT

# Your command label goes here.
ExampleCommand:

  # Your command aliases so players can do /excmd instead of typing whole /exmaplecommand.
  Aliases: [ ]

  # permission node, only people with this permission will be able to use this command.
  Permission: ''

  # Command description, completely optional.
  Description: ""

  # Required args, will be shown in the usage message between < and > and is required..
  # in this case: /examplecommand <example player>
  # the ':OnlinePlayer' suffix is to make plugin check if the given arg is an online player.
  # valid suffixes are: num, offlinePlayer, onlinePlayer.
  RequiredArgs: [ ]

  # Optiona args, will be shown in the usage message between [ and ] and is not required..
  # in this case: /examplecommand [example optional player]
  OptionalArgs: [ ]

  # Who can use commands, players, console or all!
  Who_Can_Use_Command: all

  # Commands will be executed when this command used.
  # If this command sender is player, commands starting with / will be executed as the player.
  # If the command sender is console, commands starting with / will be ignored.
  # You can use given args like this {arg:<number>}.
  # For example, if this executed command like this '/examplecommand player1 player2', {arg:0} is player1
  # and {arg:1} is player2.
  # do note if you use optional args in execute commands and is not provided the command will be ignored.
  # You can also use {player} for player name.
  ExecuteCommands: [ ]

  # Messages will be sent to sender as a reply.
  # Like execute commands, you can use {arg:<number} variable(s).
  # And {player} for player name.
  ReplyMessages:
    - 'test'
