############################################################################################################################
#                                                                                                                          #
#                                              Custom Commands Configurations                                              #
#                                                                                                                          #
############################################################################################################################
Version: 2
Command_Aliases: [CustomCommands, ccs, cuc]