############################################################################################################################
#                                                                                                                          #
#                                              Custom Commands Configurations                                              #
#                                                                                                                          #
############################################################################################################################
Version: 2
Command_Aliases: [CustomCommands, ccs, cuc]

Debug_Mode: false
# If you are facing lag and you think it's because of this plugin set this to true, this will disable the plugin from debuging to log.log file.
Is_Server_Lagging: false
